#!/bin/sh


cmd_run_main() {
  source $(dirname $0)/src/cluster_jobs
  
  local job_alias="${OPT_JOB_GROUP:-}"
  local job_groupKey="byGroup-"
  if [[ -z "${job_alias}" ]]; then
    job_alias="${OPT_JOB_NAME}"
    job_groupKey="byName-"
  fi
  local result_path_base="${WORKDIR_RESULTS}/${job_groupKey}${job_alias}"
  local oc_cmd="$(yq -r ".oc_path" ${CLUSTER_CFG_RENDERED}) --kubeconfig ${CLUSTER_KUBECONFIG} "
  local node_label=$(yq -r ".benchmark_profiles.${OPT_BENCH_PROFILE}.target_node_strategy.filter_by_label" ${GLOBAL_CONFIG})
  local node_index=$(yq -r ".benchmark_profiles.${OPT_BENCH_PROFILE}.target_node_strategy.index" ${GLOBAL_CONFIG})
  
  mkdir -p ${result_path_base}

  echo "Discovery nodes..."
  local nodes=$(${oc_cmd} get nodes -l ${node_label} -o jsonpath="{.items[${node_index}].metadata.name}")

  for node in ${nodes}; do
    echo "Running job [${OPT_JOB_NAME}] on node [${node}]"
    (
      for task_name in $(yq -r ".benchmark_profiles.${OPT_BENCH_PROFILE}.task_profiles[]?" ${GLOBAL_CONFIG}); do
        task_${task_name} ${node}
      done
    ) &
    PIDS+=($!)
  done

  echo "INFO: Waiting for tests to complete in all nodes..."
  wait "${PIDS[@]}"
  echo "INFO: Done tests ran in all nodes"

  task_prometheus_dump || true
}
